apiVersion: v1
kind: Service
metadata:
    name: gamutkart-service
    labels:
      app: gamutkart-app

spec:
  selector:
    app: gamutkart-app
  type: NodePort
  ports:
  - nodePort: 31000
    port: 8080
    targetPort: 8080
